// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.DocumentoIdentidade;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DocumentoIdentidade_Roo_Configurable {
    
    declare @type: DocumentoIdentidade: @Configurable;
    
}
