// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.Contato;
import com.jaspions.giza.domain.ContatoDataOnDemand;
import com.jaspions.giza.domain.TipoContato;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ContatoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContatoDataOnDemand: @Component;
    
    private Random ContatoDataOnDemand.rnd = new SecureRandom();
    
    private List<Contato> ContatoDataOnDemand.data;
    
    public Contato ContatoDataOnDemand.getNewTransientContato(int index) {
        Contato obj = new Contato();
        setDescricao(obj, index);
        setDescricaoTipoPersonalizado(obj, index);
        setTipoContato(obj, index);
        return obj;
    }
    
    public void ContatoDataOnDemand.setDescricao(Contato obj, int index) {
        String descricao = "descricao_" + index;
        obj.setDescricao(descricao);
    }
    
    public void ContatoDataOnDemand.setDescricaoTipoPersonalizado(Contato obj, int index) {
        String descricaoTipoPersonalizado = "descricaoTipoPersonalizado_" + index;
        obj.setDescricaoTipoPersonalizado(descricaoTipoPersonalizado);
    }
    
    public void ContatoDataOnDemand.setTipoContato(Contato obj, int index) {
        TipoContato tipoContato = TipoContato.class.getEnumConstants()[0];
        obj.setTipoContato(tipoContato);
    }
    
    public Contato ContatoDataOnDemand.getSpecificContato(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Contato obj = data.get(index);
        Long id = obj.getId();
        return Contato.findContato(id);
    }
    
    public Contato ContatoDataOnDemand.getRandomContato() {
        init();
        Contato obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Contato.findContato(id);
    }
    
    public boolean ContatoDataOnDemand.modifyContato(Contato obj) {
        return false;
    }
    
    public void ContatoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Contato.findContatoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Contato' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Contato>();
        for (int i = 0; i < 10; i++) {
            Contato obj = getNewTransientContato(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
