// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.Contato;
import com.jaspions.giza.domain.ContatoDataOnDemand;
import com.jaspions.giza.domain.ContatoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContatoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContatoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContatoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContatoIntegrationTest: @Transactional;
    
    @Autowired
    private ContatoDataOnDemand ContatoIntegrationTest.dod;
    
    @Test
    public void ContatoIntegrationTest.testCountContatoes() {
        Assert.assertNotNull("Data on demand for 'Contato' failed to initialize correctly", dod.getRandomContato());
        long count = Contato.countContatoes();
        Assert.assertTrue("Counter for 'Contato' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContatoIntegrationTest.testFindContato() {
        Contato obj = dod.getRandomContato();
        Assert.assertNotNull("Data on demand for 'Contato' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contato' failed to provide an identifier", id);
        obj = Contato.findContato(id);
        Assert.assertNotNull("Find method for 'Contato' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Contato' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContatoIntegrationTest.testFindAllContatoes() {
        Assert.assertNotNull("Data on demand for 'Contato' failed to initialize correctly", dod.getRandomContato());
        long count = Contato.countContatoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Contato', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Contato> result = Contato.findAllContatoes();
        Assert.assertNotNull("Find all method for 'Contato' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Contato' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContatoIntegrationTest.testFindContatoEntries() {
        Assert.assertNotNull("Data on demand for 'Contato' failed to initialize correctly", dod.getRandomContato());
        long count = Contato.countContatoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Contato> result = Contato.findContatoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Contato' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Contato' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContatoIntegrationTest.testFlush() {
        Contato obj = dod.getRandomContato();
        Assert.assertNotNull("Data on demand for 'Contato' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contato' failed to provide an identifier", id);
        obj = Contato.findContato(id);
        Assert.assertNotNull("Find method for 'Contato' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContato(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Contato' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContatoIntegrationTest.testMergeUpdate() {
        Contato obj = dod.getRandomContato();
        Assert.assertNotNull("Data on demand for 'Contato' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contato' failed to provide an identifier", id);
        obj = Contato.findContato(id);
        boolean modified =  dod.modifyContato(obj);
        Integer currentVersion = obj.getVersion();
        Contato merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Contato' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContatoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Contato' failed to initialize correctly", dod.getRandomContato());
        Contato obj = dod.getNewTransientContato(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Contato' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Contato' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Contato' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContatoIntegrationTest.testRemove() {
        Contato obj = dod.getRandomContato();
        Assert.assertNotNull("Data on demand for 'Contato' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contato' failed to provide an identifier", id);
        obj = Contato.findContato(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Contato' with identifier '" + id + "'", Contato.findContato(id));
    }
    
}
