// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.DocumentoIdentidade;
import com.jaspions.giza.domain.DocumentoIdentidadeDataOnDemand;
import com.jaspions.giza.domain.OrgaoEmissorDocumento;
import com.jaspions.giza.domain.OrgaoEmissorDocumentoDataOnDemand;
import com.jaspions.giza.domain.UnidadeFederativa;
import com.jaspions.giza.domain.UnidadeFederativaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DocumentoIdentidadeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DocumentoIdentidadeDataOnDemand: @Component;
    
    private Random DocumentoIdentidadeDataOnDemand.rnd = new SecureRandom();
    
    private List<DocumentoIdentidade> DocumentoIdentidadeDataOnDemand.data;
    
    @Autowired
    private OrgaoEmissorDocumentoDataOnDemand DocumentoIdentidadeDataOnDemand.orgaoEmissorDocumentoDataOnDemand;
    
    @Autowired
    private UnidadeFederativaDataOnDemand DocumentoIdentidadeDataOnDemand.unidadeFederativaDataOnDemand;
    
    public DocumentoIdentidade DocumentoIdentidadeDataOnDemand.getNewTransientDocumentoIdentidade(int index) {
        DocumentoIdentidade obj = new DocumentoIdentidade();
        setNumero(obj, index);
        setOrgaoEmissorDocumento(obj, index);
        setUnidadeFederativa(obj, index);
        return obj;
    }
    
    public void DocumentoIdentidadeDataOnDemand.setNumero(DocumentoIdentidade obj, int index) {
        String numero = "numero_" + index;
        obj.setNumero(numero);
    }
    
    public void DocumentoIdentidadeDataOnDemand.setOrgaoEmissorDocumento(DocumentoIdentidade obj, int index) {
        OrgaoEmissorDocumento orgaoEmissorDocumento = orgaoEmissorDocumentoDataOnDemand.getRandomOrgaoEmissorDocumento();
        obj.setOrgaoEmissorDocumento(orgaoEmissorDocumento);
    }
    
    public void DocumentoIdentidadeDataOnDemand.setUnidadeFederativa(DocumentoIdentidade obj, int index) {
        UnidadeFederativa unidadeFederativa = unidadeFederativaDataOnDemand.getRandomUnidadeFederativa();
        obj.setUnidadeFederativa(unidadeFederativa);
    }
    
    public DocumentoIdentidade DocumentoIdentidadeDataOnDemand.getSpecificDocumentoIdentidade(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DocumentoIdentidade obj = data.get(index);
        Long id = obj.getId();
        return DocumentoIdentidade.findDocumentoIdentidade(id);
    }
    
    public DocumentoIdentidade DocumentoIdentidadeDataOnDemand.getRandomDocumentoIdentidade() {
        init();
        DocumentoIdentidade obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DocumentoIdentidade.findDocumentoIdentidade(id);
    }
    
    public boolean DocumentoIdentidadeDataOnDemand.modifyDocumentoIdentidade(DocumentoIdentidade obj) {
        return false;
    }
    
    public void DocumentoIdentidadeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DocumentoIdentidade.findDocumentoIdentidadeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DocumentoIdentidade' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DocumentoIdentidade>();
        for (int i = 0; i < 10; i++) {
            DocumentoIdentidade obj = getNewTransientDocumentoIdentidade(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
