// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.Municipio;
import com.jaspions.giza.domain.MunicipioDataOnDemand;
import com.jaspions.giza.domain.MunicipioIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MunicipioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MunicipioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MunicipioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MunicipioIntegrationTest: @Transactional;
    
    @Autowired
    private MunicipioDataOnDemand MunicipioIntegrationTest.dod;
    
    @Test
    public void MunicipioIntegrationTest.testCountMunicipios() {
        Assert.assertNotNull("Data on demand for 'Municipio' failed to initialize correctly", dod.getRandomMunicipio());
        long count = Municipio.countMunicipios();
        Assert.assertTrue("Counter for 'Municipio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MunicipioIntegrationTest.testFindMunicipio() {
        Municipio obj = dod.getRandomMunicipio();
        Assert.assertNotNull("Data on demand for 'Municipio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Municipio' failed to provide an identifier", id);
        obj = Municipio.findMunicipio(id);
        Assert.assertNotNull("Find method for 'Municipio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Municipio' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MunicipioIntegrationTest.testFindAllMunicipios() {
        Assert.assertNotNull("Data on demand for 'Municipio' failed to initialize correctly", dod.getRandomMunicipio());
        long count = Municipio.countMunicipios();
        Assert.assertTrue("Too expensive to perform a find all test for 'Municipio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Municipio> result = Municipio.findAllMunicipios();
        Assert.assertNotNull("Find all method for 'Municipio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Municipio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MunicipioIntegrationTest.testFindMunicipioEntries() {
        Assert.assertNotNull("Data on demand for 'Municipio' failed to initialize correctly", dod.getRandomMunicipio());
        long count = Municipio.countMunicipios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Municipio> result = Municipio.findMunicipioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Municipio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Municipio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MunicipioIntegrationTest.testFlush() {
        Municipio obj = dod.getRandomMunicipio();
        Assert.assertNotNull("Data on demand for 'Municipio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Municipio' failed to provide an identifier", id);
        obj = Municipio.findMunicipio(id);
        Assert.assertNotNull("Find method for 'Municipio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMunicipio(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Municipio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MunicipioIntegrationTest.testMergeUpdate() {
        Municipio obj = dod.getRandomMunicipio();
        Assert.assertNotNull("Data on demand for 'Municipio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Municipio' failed to provide an identifier", id);
        obj = Municipio.findMunicipio(id);
        boolean modified =  dod.modifyMunicipio(obj);
        Integer currentVersion = obj.getVersion();
        Municipio merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Municipio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MunicipioIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Municipio' failed to initialize correctly", dod.getRandomMunicipio());
        Municipio obj = dod.getNewTransientMunicipio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Municipio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Municipio' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Municipio' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MunicipioIntegrationTest.testRemove() {
        Municipio obj = dod.getRandomMunicipio();
        Assert.assertNotNull("Data on demand for 'Municipio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Municipio' failed to provide an identifier", id);
        obj = Municipio.findMunicipio(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Municipio' with identifier '" + id + "'", Municipio.findMunicipio(id));
    }
    
}
