// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.Municipio;
import com.jaspions.giza.domain.MunicipioDataOnDemand;
import com.jaspions.giza.domain.UnidadeFederativa;
import com.jaspions.giza.domain.UnidadeFederativaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MunicipioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MunicipioDataOnDemand: @Component;
    
    private Random MunicipioDataOnDemand.rnd = new SecureRandom();
    
    private List<Municipio> MunicipioDataOnDemand.data;
    
    @Autowired
    private UnidadeFederativaDataOnDemand MunicipioDataOnDemand.unidadeFederativaDataOnDemand;
    
    public Municipio MunicipioDataOnDemand.getNewTransientMunicipio(int index) {
        Municipio obj = new Municipio();
        setNome(obj, index);
        setUnidadeFederativa(obj, index);
        return obj;
    }
    
    public void MunicipioDataOnDemand.setNome(Municipio obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void MunicipioDataOnDemand.setUnidadeFederativa(Municipio obj, int index) {
        UnidadeFederativa unidadeFederativa = unidadeFederativaDataOnDemand.getRandomUnidadeFederativa();
        obj.setUnidadeFederativa(unidadeFederativa);
    }
    
    public Municipio MunicipioDataOnDemand.getSpecificMunicipio(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Municipio obj = data.get(index);
        Long id = obj.getId();
        return Municipio.findMunicipio(id);
    }
    
    public Municipio MunicipioDataOnDemand.getRandomMunicipio() {
        init();
        Municipio obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Municipio.findMunicipio(id);
    }
    
    public boolean MunicipioDataOnDemand.modifyMunicipio(Municipio obj) {
        return false;
    }
    
    public void MunicipioDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Municipio.findMunicipioEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Municipio' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Municipio>();
        for (int i = 0; i < 10; i++) {
            Municipio obj = getNewTransientMunicipio(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
