// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.OrgaoEmissorDocumento;
import com.jaspions.giza.domain.OrgaoEmissorDocumentoDataOnDemand;
import com.jaspions.giza.domain.OrgaoEmissorDocumentoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OrgaoEmissorDocumentoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OrgaoEmissorDocumentoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OrgaoEmissorDocumentoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OrgaoEmissorDocumentoIntegrationTest: @Transactional;
    
    @Autowired
    private OrgaoEmissorDocumentoDataOnDemand OrgaoEmissorDocumentoIntegrationTest.dod;
    
    @Test
    public void OrgaoEmissorDocumentoIntegrationTest.testCountOrgaoEmissorDocumentoes() {
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to initialize correctly", dod.getRandomOrgaoEmissorDocumento());
        long count = OrgaoEmissorDocumento.countOrgaoEmissorDocumentoes();
        Assert.assertTrue("Counter for 'OrgaoEmissorDocumento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OrgaoEmissorDocumentoIntegrationTest.testFindOrgaoEmissorDocumento() {
        OrgaoEmissorDocumento obj = dod.getRandomOrgaoEmissorDocumento();
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to provide an identifier", id);
        obj = OrgaoEmissorDocumento.findOrgaoEmissorDocumento(id);
        Assert.assertNotNull("Find method for 'OrgaoEmissorDocumento' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'OrgaoEmissorDocumento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OrgaoEmissorDocumentoIntegrationTest.testFindAllOrgaoEmissorDocumentoes() {
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to initialize correctly", dod.getRandomOrgaoEmissorDocumento());
        long count = OrgaoEmissorDocumento.countOrgaoEmissorDocumentoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'OrgaoEmissorDocumento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<OrgaoEmissorDocumento> result = OrgaoEmissorDocumento.findAllOrgaoEmissorDocumentoes();
        Assert.assertNotNull("Find all method for 'OrgaoEmissorDocumento' illegally returned null", result);
        Assert.assertTrue("Find all method for 'OrgaoEmissorDocumento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OrgaoEmissorDocumentoIntegrationTest.testFindOrgaoEmissorDocumentoEntries() {
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to initialize correctly", dod.getRandomOrgaoEmissorDocumento());
        long count = OrgaoEmissorDocumento.countOrgaoEmissorDocumentoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<OrgaoEmissorDocumento> result = OrgaoEmissorDocumento.findOrgaoEmissorDocumentoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'OrgaoEmissorDocumento' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'OrgaoEmissorDocumento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OrgaoEmissorDocumentoIntegrationTest.testFlush() {
        OrgaoEmissorDocumento obj = dod.getRandomOrgaoEmissorDocumento();
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to provide an identifier", id);
        obj = OrgaoEmissorDocumento.findOrgaoEmissorDocumento(id);
        Assert.assertNotNull("Find method for 'OrgaoEmissorDocumento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOrgaoEmissorDocumento(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'OrgaoEmissorDocumento' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrgaoEmissorDocumentoIntegrationTest.testMergeUpdate() {
        OrgaoEmissorDocumento obj = dod.getRandomOrgaoEmissorDocumento();
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to provide an identifier", id);
        obj = OrgaoEmissorDocumento.findOrgaoEmissorDocumento(id);
        boolean modified =  dod.modifyOrgaoEmissorDocumento(obj);
        Integer currentVersion = obj.getVersion();
        OrgaoEmissorDocumento merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'OrgaoEmissorDocumento' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrgaoEmissorDocumentoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to initialize correctly", dod.getRandomOrgaoEmissorDocumento());
        OrgaoEmissorDocumento obj = dod.getNewTransientOrgaoEmissorDocumento(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'OrgaoEmissorDocumento' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'OrgaoEmissorDocumento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OrgaoEmissorDocumentoIntegrationTest.testRemove() {
        OrgaoEmissorDocumento obj = dod.getRandomOrgaoEmissorDocumento();
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrgaoEmissorDocumento' failed to provide an identifier", id);
        obj = OrgaoEmissorDocumento.findOrgaoEmissorDocumento(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'OrgaoEmissorDocumento' with identifier '" + id + "'", OrgaoEmissorDocumento.findOrgaoEmissorDocumento(id));
    }
    
}
