// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.OrgaoEmissorDocumentoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OrgaoEmissorDocumentoDataOnDemand_Roo_Configurable {
    
    declare @type: OrgaoEmissorDocumentoDataOnDemand: @Configurable;
    
}
