// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.OrgaoEmissorDocumento;
import com.jaspions.giza.domain.OrgaoEmissorDocumentoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect OrgaoEmissorDocumentoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrgaoEmissorDocumentoDataOnDemand: @Component;
    
    private Random OrgaoEmissorDocumentoDataOnDemand.rnd = new SecureRandom();
    
    private List<OrgaoEmissorDocumento> OrgaoEmissorDocumentoDataOnDemand.data;
    
    public OrgaoEmissorDocumento OrgaoEmissorDocumentoDataOnDemand.getNewTransientOrgaoEmissorDocumento(int index) {
        OrgaoEmissorDocumento obj = new OrgaoEmissorDocumento();
        setNome(obj, index);
        setSigla(obj, index);
        return obj;
    }
    
    public void OrgaoEmissorDocumentoDataOnDemand.setNome(OrgaoEmissorDocumento obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void OrgaoEmissorDocumentoDataOnDemand.setSigla(OrgaoEmissorDocumento obj, int index) {
        String sigla = "sigla_" + index;
        obj.setSigla(sigla);
    }
    
    public OrgaoEmissorDocumento OrgaoEmissorDocumentoDataOnDemand.getSpecificOrgaoEmissorDocumento(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        OrgaoEmissorDocumento obj = data.get(index);
        Long id = obj.getId();
        return OrgaoEmissorDocumento.findOrgaoEmissorDocumento(id);
    }
    
    public OrgaoEmissorDocumento OrgaoEmissorDocumentoDataOnDemand.getRandomOrgaoEmissorDocumento() {
        init();
        OrgaoEmissorDocumento obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return OrgaoEmissorDocumento.findOrgaoEmissorDocumento(id);
    }
    
    public boolean OrgaoEmissorDocumentoDataOnDemand.modifyOrgaoEmissorDocumento(OrgaoEmissorDocumento obj) {
        return false;
    }
    
    public void OrgaoEmissorDocumentoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = OrgaoEmissorDocumento.findOrgaoEmissorDocumentoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'OrgaoEmissorDocumento' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<OrgaoEmissorDocumento>();
        for (int i = 0; i < 10; i++) {
            OrgaoEmissorDocumento obj = getNewTransientOrgaoEmissorDocumento(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
