// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.Pais;
import com.jaspions.giza.domain.PaisDataOnDemand;
import com.jaspions.giza.domain.PaisIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PaisIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PaisIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PaisIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PaisIntegrationTest: @Transactional;
    
    @Autowired
    private PaisDataOnDemand PaisIntegrationTest.dod;
    
    @Test
    public void PaisIntegrationTest.testCountPaises() {
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", dod.getRandomPais());
        long count = Pais.countPaises();
        Assert.assertTrue("Counter for 'Pais' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PaisIntegrationTest.testFindPais() {
        Pais obj = dod.getRandomPais();
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pais' failed to provide an identifier", id);
        obj = Pais.findPais(id);
        Assert.assertNotNull("Find method for 'Pais' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Pais' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PaisIntegrationTest.testFindAllPaises() {
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", dod.getRandomPais());
        long count = Pais.countPaises();
        Assert.assertTrue("Too expensive to perform a find all test for 'Pais', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Pais> result = Pais.findAllPaises();
        Assert.assertNotNull("Find all method for 'Pais' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Pais' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PaisIntegrationTest.testFindPaisEntries() {
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", dod.getRandomPais());
        long count = Pais.countPaises();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Pais> result = Pais.findPaisEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Pais' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Pais' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PaisIntegrationTest.testFlush() {
        Pais obj = dod.getRandomPais();
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pais' failed to provide an identifier", id);
        obj = Pais.findPais(id);
        Assert.assertNotNull("Find method for 'Pais' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPais(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Pais' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PaisIntegrationTest.testMergeUpdate() {
        Pais obj = dod.getRandomPais();
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pais' failed to provide an identifier", id);
        obj = Pais.findPais(id);
        boolean modified =  dod.modifyPais(obj);
        Integer currentVersion = obj.getVersion();
        Pais merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Pais' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PaisIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", dod.getRandomPais());
        Pais obj = dod.getNewTransientPais(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Pais' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Pais' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Pais' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PaisIntegrationTest.testRemove() {
        Pais obj = dod.getRandomPais();
        Assert.assertNotNull("Data on demand for 'Pais' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pais' failed to provide an identifier", id);
        obj = Pais.findPais(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Pais' with identifier '" + id + "'", Pais.findPais(id));
    }
    
}
