// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.Pais;
import com.jaspions.giza.domain.PaisDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PaisDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PaisDataOnDemand: @Component;
    
    private Random PaisDataOnDemand.rnd = new SecureRandom();
    
    private List<Pais> PaisDataOnDemand.data;
    
    public Pais PaisDataOnDemand.getNewTransientPais(int index) {
        Pais obj = new Pais();
        setNome(obj, index);
        setSigla(obj, index);
        return obj;
    }
    
    public void PaisDataOnDemand.setNome(Pais obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void PaisDataOnDemand.setSigla(Pais obj, int index) {
        String sigla = "sigla_" + index;
        obj.setSigla(sigla);
    }
    
    public Pais PaisDataOnDemand.getSpecificPais(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Pais obj = data.get(index);
        Long id = obj.getId();
        return Pais.findPais(id);
    }
    
    public Pais PaisDataOnDemand.getRandomPais() {
        init();
        Pais obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Pais.findPais(id);
    }
    
    public boolean PaisDataOnDemand.modifyPais(Pais obj) {
        return false;
    }
    
    public void PaisDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Pais.findPaisEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Pais' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Pais>();
        for (int i = 0; i < 10; i++) {
            Pais obj = getNewTransientPais(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
