// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.PessoaFisica;
import com.jaspions.giza.domain.PessoaFisicaDataOnDemand;
import com.jaspions.giza.domain.PessoaFisicaIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PessoaFisicaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PessoaFisicaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PessoaFisicaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PessoaFisicaIntegrationTest: @Transactional;
    
    @Autowired
    private PessoaFisicaDataOnDemand PessoaFisicaIntegrationTest.dod;
    
    @Test
    public void PessoaFisicaIntegrationTest.testCountPessoaFisicas() {
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to initialize correctly", dod.getRandomPessoaFisica());
        long count = PessoaFisica.countPessoaFisicas();
        Assert.assertTrue("Counter for 'PessoaFisica' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PessoaFisicaIntegrationTest.testFindPessoaFisica() {
        PessoaFisica obj = dod.getRandomPessoaFisica();
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to provide an identifier", id);
        obj = PessoaFisica.findPessoaFisica(id);
        Assert.assertNotNull("Find method for 'PessoaFisica' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PessoaFisica' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PessoaFisicaIntegrationTest.testFindAllPessoaFisicas() {
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to initialize correctly", dod.getRandomPessoaFisica());
        long count = PessoaFisica.countPessoaFisicas();
        Assert.assertTrue("Too expensive to perform a find all test for 'PessoaFisica', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PessoaFisica> result = PessoaFisica.findAllPessoaFisicas();
        Assert.assertNotNull("Find all method for 'PessoaFisica' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PessoaFisica' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PessoaFisicaIntegrationTest.testFindPessoaFisicaEntries() {
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to initialize correctly", dod.getRandomPessoaFisica());
        long count = PessoaFisica.countPessoaFisicas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PessoaFisica> result = PessoaFisica.findPessoaFisicaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PessoaFisica' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PessoaFisica' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PessoaFisicaIntegrationTest.testFlush() {
        PessoaFisica obj = dod.getRandomPessoaFisica();
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to provide an identifier", id);
        obj = PessoaFisica.findPessoaFisica(id);
        Assert.assertNotNull("Find method for 'PessoaFisica' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPessoaFisica(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PessoaFisica' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PessoaFisicaIntegrationTest.testMergeUpdate() {
        PessoaFisica obj = dod.getRandomPessoaFisica();
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to provide an identifier", id);
        obj = PessoaFisica.findPessoaFisica(id);
        boolean modified =  dod.modifyPessoaFisica(obj);
        Integer currentVersion = obj.getVersion();
        PessoaFisica merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PessoaFisica' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PessoaFisicaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to initialize correctly", dod.getRandomPessoaFisica());
        PessoaFisica obj = dod.getNewTransientPessoaFisica(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PessoaFisica' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'PessoaFisica' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PessoaFisicaIntegrationTest.testRemove() {
        PessoaFisica obj = dod.getRandomPessoaFisica();
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PessoaFisica' failed to provide an identifier", id);
        obj = PessoaFisica.findPessoaFisica(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PessoaFisica' with identifier '" + id + "'", PessoaFisica.findPessoaFisica(id));
    }
    
}
