// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspions.giza.domain;

import com.jaspions.giza.domain.Pais;
import com.jaspions.giza.domain.PaisDataOnDemand;
import com.jaspions.giza.domain.UnidadeFederativa;
import com.jaspions.giza.domain.UnidadeFederativaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UnidadeFederativaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UnidadeFederativaDataOnDemand: @Component;
    
    private Random UnidadeFederativaDataOnDemand.rnd = new SecureRandom();
    
    private List<UnidadeFederativa> UnidadeFederativaDataOnDemand.data;
    
    @Autowired
    private PaisDataOnDemand UnidadeFederativaDataOnDemand.paisDataOnDemand;
    
    public UnidadeFederativa UnidadeFederativaDataOnDemand.getNewTransientUnidadeFederativa(int index) {
        UnidadeFederativa obj = new UnidadeFederativa();
        setNome(obj, index);
        setPais(obj, index);
        setSigla(obj, index);
        return obj;
    }
    
    public void UnidadeFederativaDataOnDemand.setNome(UnidadeFederativa obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void UnidadeFederativaDataOnDemand.setPais(UnidadeFederativa obj, int index) {
        Pais pais = paisDataOnDemand.getRandomPais();
        obj.setPais(pais);
    }
    
    public void UnidadeFederativaDataOnDemand.setSigla(UnidadeFederativa obj, int index) {
        String sigla = "sigla_" + index;
        obj.setSigla(sigla);
    }
    
    public UnidadeFederativa UnidadeFederativaDataOnDemand.getSpecificUnidadeFederativa(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UnidadeFederativa obj = data.get(index);
        Long id = obj.getId();
        return UnidadeFederativa.findUnidadeFederativa(id);
    }
    
    public UnidadeFederativa UnidadeFederativaDataOnDemand.getRandomUnidadeFederativa() {
        init();
        UnidadeFederativa obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UnidadeFederativa.findUnidadeFederativa(id);
    }
    
    public boolean UnidadeFederativaDataOnDemand.modifyUnidadeFederativa(UnidadeFederativa obj) {
        return false;
    }
    
    public void UnidadeFederativaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UnidadeFederativa.findUnidadeFederativaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UnidadeFederativa' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UnidadeFederativa>();
        for (int i = 0; i < 10; i++) {
            UnidadeFederativa obj = getNewTransientUnidadeFederativa(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
